#ayalat Abril 2020
---
- name: Control de reinicio de servidores
  hosts: all
  tasks:
  - debug:
      msg: " {{ ansible_fqdn }} - {{ ansible_hostname }} : hace más de  {{ ansible_uptime_seconds }} segundos que no se reinicia. Toca reiniciarlo."
    when: ansible_uptime_seconds > 3024000
