#ayalat Abril 2020
---
- name: Control de comunicación con servidores
  hosts: localhost
  gather_facts: false
  tasks:
    - name: notificar_slack
      shell: ansible all -m setup | grep " UNREACHABLE\!" | awk '{print $1}'
      register: shell_output

    - debug: var=shell_output.stdout_lines|list

    - name: Avisar por Slack
      slack:
        domain: "{{ slack_domain }}"
        token: "{{ slack_token_lab }}"
        msg: "ANSIBLE ERROR !!! Servidor/es {{ shell_output.stdout_lines|list | replace('] ',' ') | replace('[u','') }} no responde/n."
      when: shell_output.stdout != ""
      delegate_to: localhost
