#ayalat Abril 2020
---
- name: Control de comunicación con servidores
  hosts: localhost
  gather_facts: false
  tasks:
    - name: notificar_slack
      shell: ansible all -m setup | grep " UNREACHABLE\!" | awk '{print $1}'
      register: shell_output

    - debug: var=shell_output.stdout_lines

