#ayalat Abril 2020
---
- name: Control de comunicación con servidores
  hosts: localhost
  gather_facts: false
  tasks:
    - name: notificar_slack
      shell: ansible all -m setup | grep " UNREACHABLE\!" | awk '{print $1}'
      register: shell_output

    - debug:
        msg: "{{ shell_output }} | replace ('Ke30=[4D[K[KeyJ1dWlkIjogIjliMGM5MTZiLWIzNzQtNGVjNi04OTZhLTlhMGMxODNmYzRmOCJ9[64D[K[1;31m','')"
      when: shell_output.stdout is defined

