#ayalat Abril 2020
---
- name: Unix
  hosts: unix
  gather_facts: false
  tasks:
    - name: Hacerles ping
      ping:
    
    - name: Checking web del Ansible Tower Lab
      win_uri:
        url: https://ansibletowerlab
        validate_certs: no
