#ayalat Abril 2020
---
- name: Recogida de los ficheros de configuracion de los servers UNIX
  hosts: unix
  gather_facts: true
  tasks:
    - name: copia del fichero /etc/hosts
      fetch:
        src: /etc/hosts
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes

    - name: copia del fichero /etc/resolv.conf
      fetch:
        src: /etc/resolv.conf
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes
