#ayalat Abril 2020
---
- name: Unix
  hosts: unix
  gather_facts: false
  tasks:
    - name: Hacerles ping
      ping:

    - name: Checking web del Ansible Tower Lab
      uri:
        url: https://redhattowerlab
        validate_certs: no

    - name: Checking web de Google
      uri:
        url: https://www.google.es/
#        validate_certs: no

    - name: Checking web del Smartlis entorno Lab
      win_uri:
        url: http://smartlis.lan/smartlis

    - name: Checking web del Smartlis Twisted entorno Lab
      win_uri:
        url: http://test.smartlis.lan/smartlis
