#ayalat Abril 2020
---
- name: unix
  hosts: unix
  gather_facts: false
  tasks:
    - name: copia del fichero /etc/hosts
      fetch:
        src: /etc/hosts
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes

    - name: copia del fichero /etc/resolv.conf
      fetch:
        src: /etc/resolv.conf
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes
