#ayalat Abril 2020
---
- name: unix
  hosts: unix
  gather_facts: false
  tasks:
    - name: copia del fichero /etc/hosts
      fetch:
        src: /etc/hosts
        dest: {{ inventory_hostname }}/
                #dest: /root/backup_config/{{ inventory_hostname }}/
        flat: yes

    - name: copia del fichero /etc/resolv.conf
      fetch:
        src: /etc/resolv.conf
        dest: {{ inventory_hostname }}/
        #dest: /root/backup_config/{{ inventory_hostname }}/
        flat: yes
