#ayalat Abril 2020
---
- name: Buscar actualizaciones de windows
  hosts: windows
  tasks:
    - name: Hacerles ping
      win_ping:

    - name: Buscar actualizaciones e informar en fichero
      win_updates:
        category_names:
          - Application
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
        state: searched
        log_path: C:\{{ inventory_hostname }}_ansible_wu_searched.txt

    - name: Copiar fichero a servidor ansible
      fetch:
        src: C:\{{ inventory_hostname }}_ansible_wu_searched.txt
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes


