#ayalat Abril 2020
---
- name: windows
  hosts: windows
  gather_facts: false
  tasks:
    - name: Copy c:\windows\system32\drivers\etc\hosts
      fetch:
        src: c:\windows\system32\drivers\etc\hosts
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes

