#ayalat Abril 2020
---
- name: Windows
  hosts: windows
  gather_facts: false
  tasks:
    - name: Hacerles ping
      win_ping:

    - name: Search and download Windows updates without installing them
      win_updates:
        category_names:
          - Application
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
#        blacklist:
#          - Microsoft Silverlight
        state: downloaded
        log_path: C:\{{ inventory_hostname }}_ansible_wu_searched_and_downloaded.txt

    - name: Copiar fichero a servidor ansible
      fetch:
        src: C:\{{ inventory_hostname }}_ansible_wu_searched_and_downloaded.txt
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes

    - name: Install Windows Updates and reboot
      win_updates:
        category_names:
          - Application
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
#        blacklist:
#          - Microsoft Silverlight
        reboot: yes
        reboot_timeout: 300
        log_path: C:\{{ inventory_hostname }}_ansible_wu_updated.txt

    - name: Copiar fichero a servidor ansible
      fetch:
        src: C:\{{ inventory_hostname }}_ansible_wu_updated.txt
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes

