#ayalat Abril 2020
---
- name: Windows
  hosts: windows
  gather_facts: false
  tasks:
    - name: Hacerles ping
      win_ping:

    - name: Search-only, return list of found updates (if any), log to C:\ansible_wu_searched.txt
      win_updates:
        category_names:
          - Application
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
        blacklist:
          - Microsoft Silverlight
        state: searched
        log_path: C:\ansible_wu_searched.txt


