#ayalat Abril 2020
---
#more info in https://docs.ansible.com/ansible/latest/modules/win_updates_module.html

- name: Buscar actualizaciones de windows
  hosts: windows
  tasks:
    - name: Hacerles ping
      win_ping:

    - name: Ensure that WinRM is started when the system has settled
      win_service:
        name: WinRM
        start_mode: delayed

    - name: Check if Windows Update is installed
      win_service:
        name: wuauserv
        register: service_info

    - name: Set service startup mode to manual
      win_service:
        name: wuauserv
        start_mode: manual
       # state: started

    - name: Buscar actualizaciones e informar en fichero
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        state: searched
        log_path: C:\{{ inventory_hostname }}_ansible_wu_searched.txt

    - name: Copiar fichero a servidor ansible
      fetch:
        src: C:\{{ inventory_hostname }}_ansible_wu_searched.txt
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes

    - name: Avisaré por Slack lab
      slack:
        domain: "{{ slack_domain }}"
        token: "{{ slack_token_lab }}"
        msg: "ANSIBLE INFO4Toni !!! Dejo en /ansible/backup_configuracion/{{ inventory_hostname }}/{{ inventory_hostname }}_ansible_wu_searched.txt el informe de parches para actualizar. Ruego le eches un vistazo y sino dices nada, una vez al mes, se actualizarán."
      delegate_to: localhost
