#ayalat Abril 2020
---
- name: Windows monitorizacion continua común
  hosts: windows
  gather_facts: false
  tasks:
    - name: Hacerles ping
      win_ping:

    - name: Ensure that WinRM is started when the system has settled
      win_service:
        name: WinRM
        start_mode: delayed

    - name: Check if Windows Update is installed
      win_service:
        name: wuauserv
        register: service_info

    - name: Set service startup mode to manual
      win_service:
        name: wuauserv
        start_mode: manual
       # state: started

    - name: Checking web de Google
      win_uri:
        url: https://www.google.es/
#        validate_certs: no



- name: Windows monitorizacion continua win10lab
  hosts: win10lab
  gather_facts: false
  tasks:

    - name: Checking web del Ansible Tower Lab
      win_uri:
        url: https://ansibletowerlab
        validate_certs: no

    - name: Checking web del Smartlis entorno Lab
      win_uri:
        url: http://smartlis.lan/smartlis

    - name: Checking web del Smartlis Twisted entorno Lab
      win_uri:
        url: http://test.smartlis.lan/smartlis

