#ayalat Abril 2020
---
- name: windows
  hosts: windows
  gather_facts: false
  tasks:
    - name: Specifying a path directly
      fetch:
        src: c:\windows\system32\drivers\etc\hosts
        dest: /root/backup_config/{{ inventory_hostname }}/
        flat: yes
