#ayalat Abril 2020
---
- name: Windows
  hosts: windows
  gather_facts: false
  tasks:
    - name: Hacerles ping
      win_ping:

    - name: Ensure that WinRM is started when the system has settled
      win_service:
        name: WinRM
        start_mode: delayed

    - name: Check if Windows Update is installed
      win_service:
        name: wuauserv
        register: service_info

    - name: Set service startup mode to manual
      win_service:
        name: wuauserv
        start_mode: manual
       # state: started

    - name: Search and download Windows updates without installing them
      win_updates:
        category_names:
          - Application
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
        state: downloaded
        log_path: C:\{{ inventory_hostname }}_ansible_wu_searched_and_downloaded.txt

    - name: Copiar fichero a servidor ansible
      fetch:
        src: C:\{{ inventory_hostname }}_ansible_wu_searched_and_downloaded.txt
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes

    - name: Avisaré por Slack lab
      slack:
        domain: "{{ slack_domain }}"
        token: "{{ slack_token_lab }}"
        msg: "ANSIBLE INFO4Toni !!! Me bajo los parches y dejo el informe en /ansible/backup_configuracion/{{ inventory_hostname }}/{{ inventory_hostname }}_ansible_wu_searched_and_downloaded.txt. Me dispongo a instalarlos ahoramismo ..."
      delegate_to: localhost


    - name: Install Windows Updates and reboot
      win_updates:
        category_names:
          - Application
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
        reboot: yes
        reboot_timeout: 300
        log_path: C:\{{ inventory_hostname }}_ansible_wu_updated.txt

    - name: Copiar fichero a servidor ansible
      fetch:
        src: C:\{{ inventory_hostname }}_ansible_wu_updated.txt
        dest: /ansible/backup_configuracion/{{ inventory_hostname }}/
        flat: yes

    - name: Avisaré por Slack lab
      slack:
        domain: "{{ slack_domain }}"
        token: "{{ slack_token_lab }}"
        msg: "ANSIBLE INFO4Toni !!! Parches actualizados !!! Dejo en /ansible/backup_configuracion/{{ inventory_hostname }}/{{ inventory_hostname }}_ansible_wu_updated.txt el informe."
      delegate_to: localhost


